apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: nfs-acl
spec:
  serviceAccountName: nfs-sa
  securityContext:
    runAsUser: 1002
    runAsGroup: 1002
    fsGroup: 1002
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /mnt/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-pod-b
