apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pod-a
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.0.22
    path: /var/nfsshare/pod-a
