apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pod-a
  namespace: nfs-acl
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-pod-a
